data_science_books = {
    "Python for Data Science": 15,
    "Machine Learning Fundamentals": 8,
    "Deep Learning with Neural Networks": 12,
    "Statistics for Data Analysis": 20,
    "Data Visualization Essentials": 9,
    "Pandas and NumPy Mastery": 14,
    "Applied Data Science": 6,
    "Big Data Analytics": 18,
    "Data Mining Concepts": 10,
    "AI for Data Scientists": 7,

    "Regression Analysis Explained": 16,
    "Time Series Forecasting": 11,
    "Natural Language Processing Basics": 5,
    "Computer Vision Foundations": 13,
    "Exploratory Data Analysis": 17,
    "Data Cleaning Techniques": 8,
    "Feature Engineering Guide": 19,
    "Predictive Modeling": 9,
    "Probability for Data Science": 14,
    "SQL for Data Analysts": 6,

    "R for Data Science": 15,
    "Bayesian Statistics Made Easy": 7,
    "Dimensionality Reduction": 12,
    "Clustering Algorithms": 18,
    "Recommendation Systems": 10,
    "Decision Trees and Random Forests": 5,
    "Support Vector Machines": 16,
    "Neural Network Architectures": 11,
    "Optimization Methods": 9,
    "Data Ethics and Privacy": 20,

    "Cloud Computing for Data Science": 8,
    "Spark for Big Data": 14,
    "Hadoop Essentials": 6,
    "Streaming Data Processing": 17,
    "Data Warehousing Concepts": 10,
    "Business Intelligence Tools": 13,
    "Power BI for Analysts": 7,
    "Tableau Data Visualization": 15,
    "Dashboards and Reporting": 9,
    "Kaggle Projects Guide": 18,

    "AutoML Techniques": 11,
    "Model Evaluation Metrics": 5,
    "A/B Testing for Data Science": 16,
    "Causal Inference": 12,
    "Reinforcement Learning Intro": 19,
    "Graph Analytics": 8,
    "Anomaly Detection": 14,
    "Data Science Capstone Projects": 6,
    "Real World Machine Learning": 17,
    "Explainable AI": 10,

    "Data Science with Excel": 9,
    "Mathematics for Machine Learning": 15,
    "Data Pipelines and ETL": 7,
    "NoSQL Databases for Data Science": 13,
    "Data Science in Healthcare": 18,
    "Financial Data Analysis": 11,
    "Marketing Analytics": 5,
    "Social Media Data Mining": 16,
    "Geospatial Data Analysis": 12,
    "Data Science Interview Prep": 20,

    "Edge AI and IoT Analytics": 8,
    "Time Series with Python": 14,
    "Advanced SQL Analytics": 6,
    "Text Mining Techniques": 17,
    "Image Processing with Python": 10,
    "Statistical Learning Theory": 9,
    "Data Science in Education": 15,
    "Energy Data Analytics": 7,
    "Sports Analytics": 13,
    "Smart Cities Data Science": 18
}